spring:
  application:
    name: jobicy-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: jobicy-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.hmeclazcke.jobsearchplatform.contracts
        spring.json.value.default.type: com.hmeclazcke.jobsearchplatform.contracts.search.event.SearchRequestedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false

  data:
    redis:
      url: redis://localhost:6379

  cache:
    type: redis
    redis:
      time-to-live: 30m

server:
  port: 8082

app:
  jobicy:
    base-url: https://jobicy.com

  kafka:
    topics:
      search-requested: search.requested.v1
      provider-results: provider.results.v1
      provider-failed: provider.failed.v1

resilience4j:
  circuitbreaker:
    instances:
      jobicy:
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true