spring:
  application:
    name: jobicy-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: jobicy-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.hmeclazcke.jobsearchplatform.contracts
        spring.json.value.default.type: com.hmeclazcke.jobsearchplatform.contracts.SearchRequestedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8082

app:
  jobicy:
    base-url: https://jobicy.com
  kafka:
    topics:
      search-requested: search.requested.v1
      provider-results: provider.results.v1
      provider-failed: provider.failed.v1