spring:
  application:
    name: search-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  data:
    redis:
      url: redis://localhost:6379

server:
  port: 8081

app:
  kafka:
    topics:
      search-requested: search.requested.v1