spring:
  application:
    name: internal-jobs-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: internal-jobs-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.hmeclazcke.jobsearchplatform.contracts
        spring.json.value.default.type: com.hmeclazcke.jobsearchplatform.contracts.search.event.SearchRequestedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false

  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/job-search-platform}

server:
  port: 8084

app:
  kafka:
    topics:
      search-requested: search.requested.v1
      provider-results: provider.results.v1
      provider-failed: provider.failed.v1